name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: cache stack
      id: cache-stack-ghc-2
      uses: actions/cache@v1
      with:
        path: ~/AppData/Local/Programs/stack
        key: cache-stack-ghc-key-2
    - name: install stack
      run: |
        choco install haskell-stack
    - name: Cache stack root
      id: cache-stack-3
      uses: actions/cache@v1
      with:
        path: sr
        key: stack-root-3
    - name: Build CurlRunnings
      env:
        STACK_ROOT: ${{ github.workspace }}/sr
      run: |
        $install_path = stack path --local-bin
        stack install
        new-item ${{ github.workspace }}/output -itemtype directory
        move-item $install_path/curl-runnings.exe ${{ github.workspace }}/output
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/output/curl-runnings.exe
        asset_name: curl-runnings.exe
        asset_content_type: application/octet-stream 
