name: Windows Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
#     - name: Set environment variables
#       run: |
#         echo "$GITHUB_WORKSPACE"
#         echo "::set-env name=STACK_ROOT::$GITHUB_WORKSPACE/sr"
    - name: cache stack
      id: cache-stack-ghc-2
      uses: actions/cache@v1
      with:
        path: ~/AppData/Local/Programs/stack
        key: cache-stack-ghc-key-2
    - name: install stack
      run: |
        choco install haskell-stack
    - name: Cache stack root
      id: cache-stack-3
      uses: actions/cache@v1
      with:
        path: sr
        key: stack-root-3
    - name: Build CurlRunnings
      env:
        STACK_ROOT: ${{ github.workspace }}/sr
      run: |
        $install_path = stack path --local-bin
        echo ::set-env install_path=$install_path/curl-runnings.exe
        stack install
        new-item ${{ github.workspace }}/output -itemtype directory
        move-item ${env.install_path}/curl-runnings.exe ${{ github.workspace }}/output 
    - name: store binary
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: ${{ github.workspace }}/output/curl-runnings.exe
