name: Windows Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
#     - name: Set environment variables
#       run: |
#         echo "$GITHUB_WORKSPACE"
#         echo "::set-env name=STACK_ROOT::$GITHUB_WORKSPACE/sr"
    - name: install stack
      run: |
        choco install haskell-stack
    - name: Cache stack root
      id: cache-stack-3
      uses: actions/cache@v1
      with:
        path: sr
        key: stack-root-3
    - name: Build CurlRunnings
      env:
        STACK_ROOT: ${{ github.workspace }}/sr
      run: |
        stack install
    - name: store binary
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: ${{ github.workspace }}/curl-runnings
